import { useState, useEffect } from 'react';
import {
  Activity,
  BarChart2,
  Zap,
  User,
  X,
  CheckCircle,
  TrendingUp,
  ArrowRight
} from 'lucide-react';
import { TemplateProps } from '../types';
import { useTemplate } from '../../src/contexts/TemplateContext';
import { getConfig } from '../../src/config/config';

const MARKET_INDICATORS = [
  { name: 'S&P 500', change: '+0.42%', isUp: true },
  { name: 'NASDAQ', change: '-0.15%', isUp: false },
  { name: 'Dow Jones', change: '+0.62%', isUp: true },
  { name: 'Semiconductors', change: '+1.28%', isUp: true },
  { name: 'Banking', change: '-0.21%', isUp: false },
  { name: 'AI Sector', change: '+0.98%', isUp: true },
  { name: 'Automotive', change: '-0.31%', isUp: false },
  { name: 'Robotics', change: '+1.45%', isUp: true },
  { name: 'Energy', change: '+0.57%', isUp: true },
  { name: 'Biotech', change: '-0.42%', isUp: false },
  { name: 'Steel', change: '+0.83%', isUp: true },
  { name: 'Trading', change: '+0.24%', isUp: true },
];

const TICKER_ITEMS = [
  { ticker: 'AAPL', name: 'Apple', change: '+1.18%', isUp: true },
  { ticker: 'MSFT', name: 'Microsoft', change: '+0.1%', isUp: true },
  { ticker: 'NVDA', name: 'NVIDIA', change: '+2.0%', isUp: true },
  { ticker: 'TSLA', name: 'Tesla', change: '+1.85%', isUp: true },
  { ticker: 'META', name: 'META', change: '+1.14%', isUp: true },
  { ticker: 'AMZN', name: 'Amazon', change: '+0.45%', isUp: true },
  { ticker: 'GOOGL', name: 'Alphabet', change: '+0.5%', isUp: true },
  { ticker: 'JPM', name: 'JPMorgan', change: '+0.27%', isUp: true },
  { ticker: 'NFLX', name: 'Netflix', change: '+0.92%', isUp: true },
  { ticker: 'XOM', name: 'ExxonMobil', change: '+1.38%', isUp: true },
];

const ANALYSIS_STEPS = [
  'Gathering historical price and volume data',
  'Analyzing trend and momentum indicators',
  'Evaluating volatility patterns',
  'Processing technical indicators',
  'Computing risk assessments',
  'Generating comprehensive report',
];

const FEATURES = [
  {
    icon: Activity,
    title: 'AI Stock Analysis',
  },
  {
    icon: BarChart2,
    title: 'Market Forecast',
  },
  {
    icon: Zap,
    title: 'Instant Diagnostics',
  },
];

const REVIEWS = [
  {
    text: 'Even from a professional perspective, this AI system is highly valuable, especially its sector analysis capabilities.',
    author: 'Emily Davis',
    title: 'Equity Analyst',
    location: 'Chicago',
  },
  {
    text: 'The real-time analysis and instant diagnostics have completely transformed how I approach stock research and trading decisions.',
    author: 'Michael Chen',
    title: 'Portfolio Manager',
    location: 'NYC',
  },
  {
    text: 'Incredibly accurate predictions and the interface is so intuitive. This tool has become essential for my daily trading routine.',
    author: 'Sarah Johnson',
    title: 'Day Trader',
    location: 'San Francisco',
  },
];

const DISCLOSURE_SECTIONS = [
  {
    title: 'Purpose of This Service',
    content: 'All information, analysis, and data provided on this site are intended for educational and research purposes. They are created to provide a learning experience using AI technology.',
  },
  {
    title: 'Nature of the Information',
    content: 'The content is designed for general knowledge sharing and does not instruct or recommend any specific decisions or actions. Users should rely on this within the context of their own learning objectives.',
  },
  {
    title: 'About AI Analysis Results',
    content: 'The results and figures generated by AI are automatically produced and serve only as educational examples. They do not predict actual outcomes or real-world accuracy and should be used as reference material to deepen understanding.',
  },
  {
    title: 'Regarding Data Reliability',
    content: 'The data presented is created based on reliable information sources; however, accuracy, timeliness, and completeness are not guaranteed. Interpretation of the information is the responsibility of the user.',
  },
  {
    title: 'Legal Position',
    content: 'This service provides general knowledge sharing from an educational perspective and does not serve as financial or professional advice or guidance.',
  },
];

export default function AIStockAnalyzer({ templateId, visitorId }: TemplateProps) {
  const { trackConversion, trackClick, trafficLink, sendGA4Event } = useTemplate();
  const [tickerInput, setTickerInput] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [currentStep, setCurrentStep] = useState(0);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [analyzedSymbol, setAnalyzedSymbol] = useState('');
  const [activeReview, setActiveReview] = useState(0);
  const [typedText, setTypedText] = useState('');
  const fullText = 'Organizing fundamentals and technicals';

  useEffect(() => {
    console.log('[AI Stock Analyzer] Traffic link data:', trafficLink);
  }, [trafficLink]);

  useEffect(() => {
    const config = getConfig();
    const apiUrl = config.api.baseUrl || '';
    const script = document.createElement('script');
    script.src = `${apiUrl}/api/analytics/tracking-script/${templateId}`;
    script.async = true;
    document.head.appendChild(script);

    return () => {
      document.head.removeChild(script);
    };
  }, [templateId]);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveReview((prev) => (prev + 1) % REVIEWS.length);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    let currentIndex = 0;
    const typingInterval = setInterval(() => {
      if (currentIndex <= fullText.length) {
        setTypedText(fullText.slice(0, currentIndex));
        currentIndex++;
      } else {
        clearInterval(typingInterval);
        setTimeout(() => {
          currentIndex = 0;
          setTypedText('');
        }, 2000);
      }
    }, 100);

    return () => clearInterval(typingInterval);
  }, []);

  const handleAnalyzeClick = () => {
    const symbol = tickerInput.trim().toUpperCase() || 'AAPL';
    setAnalyzedSymbol(symbol);

    console.log('[AI Stock Analyzer] Analysis started for:', symbol);
    console.log('[AI Stock Analyzer] Current traffic link:', trafficLink);

    sendGA4Event('Bdd');
    trackClick('analyze-button', 'button');

    setIsAnalyzing(true);
    setShowModal(true);
    setAnalysisProgress(0);
    setCurrentStep(0);
    setCompletedSteps([]);

    const interval = setInterval(() => {
      setAnalysisProgress(prev => {
        const newProgress = prev + 1;

        const stepIndex = Math.floor((newProgress / 100) * ANALYSIS_STEPS.length);
        if (stepIndex !== currentStep && stepIndex < ANALYSIS_STEPS.length) {
          if (currentStep > 0) {
            setCompletedSteps(prev => [...prev, currentStep - 1]);
          }
          setCurrentStep(stepIndex + 1);
        }

        if (newProgress >= 100) {
          clearInterval(interval);
          setTimeout(() => {
            setCompletedSteps(prev => [...prev, ANALYSIS_STEPS.length - 1]);
            setTimeout(() => {
              setIsAnalyzing(false);
            }, 500);
          }, 500);
        }

        return Math.min(newProgress, 100);
      });
    }, 30);
  };

  const handleConversionClick = () => {
    console.log('[AI Stock Analyzer] Button clicked');
    console.log('[AI Stock Analyzer] TrafficLink data:', trafficLink);

    sendGA4Event('Add');
    trackClick('whatsapp-cta', 'button');
    trackConversion('whatsapp');

    if (trafficLink?.url) {
      console.log('[AI Stock Analyzer] Opening traffic link URL:', trafficLink.url);

      if (typeof window !== 'undefined' && window.gtag_report_conversion) {
        window.gtag_report_conversion(trafficLink.url);
      } else {
        window.location.href = trafficLink.url;
      }
    } else {
      console.warn('[AI Stock Analyzer] No traffic link URL available. No action taken.');
    }
  };

  const closeModal = () => {
    setShowModal(false);
    setIsAnalyzing(false);
    setAnalysisProgress(0);
    setCurrentStep(0);
    setCompletedSteps([]);
  };

  return (
    <div className="min-h-screen bg-black text-white relative overflow-x-hidden">
      <section className="relative bg-gradient-to-b from-slate-900/80 via-blue-950 to-black px-6 py-8 sm:py-12 md:py-16">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-2">
              <Activity className="w-5 h-5 bg-gradient-to-r from-cyan-400 to-blue-500 rounded" style={{ WebkitMaskImage: 'linear-gradient(to right, cyan, blue)' }} />
              <span className="text-cyan-400 font-semibold text-sm sm:text-base">AI Stock Analyzer</span>
            </div>
            <div className="overflow-hidden max-w-[200px] sm:max-w-xs">
              <div className="flex animate-marquee-reverse whitespace-nowrap text-xs">
                {[...MARKET_INDICATORS, ...MARKET_INDICATORS].map((item, index) => (
                  <span key={index} className={`mx-3 font-mono ${item.isUp ? 'text-emerald-400' : 'text-red-400'}`}>
                    {item.name} {item.change}
                  </span>
                ))}
              </div>
            </div>
          </div>

          <div className="text-center mb-10">
            <h1 className="text-5xl sm:text-6xl md:text-7xl font-extrabold mb-4 bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
              AI Stock Assistant
            </h1>
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold mb-6 text-white">
              Next-Generation Stock Analysis
            </h2>
            <div className="h-8 flex items-center justify-center">
              <p className="text-cyan-400 text-base sm:text-lg font-mono">
                {typedText}<span className="animate-pulse">|</span>
              </p>
            </div>

            <div
              className="inline-flex items-center gap-3 rounded-full px-6 py-3 mt-8 mb-10 border-2 border-transparent"
              style={{
                background: 'linear-gradient(rgba(12, 25, 45, 0.38), rgba(12, 25, 45, 0.38)) padding-box, linear-gradient(135deg, rgba(34, 176, 255, 0.85), rgba(111, 212, 255, 0.25)) border-box',
                boxShadow: '0 0 20px rgba(34, 176, 255, 0.35), 0 0 40px rgba(34, 176, 255, 0.25)'
              }}
            >
              <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></div>
              <span className="text-sm font-medium">
                Total <span className="text-cyan-400 font-bold">4,868</span> users online
              </span>
            </div>
          </div>

          <div className="max-w-2xl mx-auto">
            <h3 className="text-lg sm:text-xl font-semibold mb-4 text-center">Start Stock Analysis</h3>
            <div className="bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-2xl p-4 sm:p-6">
              <input
                type="text"
                value={tickerInput}
                onChange={(e) => setTickerInput(e.target.value)}
                className="w-full px-4 py-3 bg-white border border-slate-300 rounded-lg text-gray-900 placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent mb-4 text-base"
                placeholder="Stock Symbol (e.g. TSLA, AAPL)"
              />
              <button
                onClick={handleAnalyzeClick}
                className="w-full bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600 text-white py-3 px-6 rounded-lg font-semibold text-base sm:text-lg transition-all shadow-lg hover:shadow-cyan-500/50 active:scale-[0.98] flex items-center justify-center gap-2"
              >
                <span>Analyze</span>
                <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      </section>

      <section className="py-8 sm:py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-3 gap-3 sm:gap-6">
            {FEATURES.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div
                  key={index}
                  className="bg-slate-800/50 backdrop-blur-sm border border-cyan-500/20 rounded-xl p-3 sm:p-6 hover:border-cyan-500/40 transition-all duration-300"
                >
                  <div className="w-10 h-10 sm:w-12 sm:h-12 bg-slate-900 border-2 rounded-full flex items-center justify-center mb-2 sm:mb-3 mx-auto border-transparent"
                    style={{
                      borderImage: 'linear-gradient(135deg, #22B0FF, #6FD4FF) 1'
                    }}
                  >
                    <Icon className="w-5 h-5 sm:w-6 sm:h-6 bg-gradient-to-r from-cyan-400 to-blue-500 text-transparent" style={{ filter: 'drop-shadow(0 0 8px rgba(34, 176, 255, 0.6))' }} />
                  </div>
                  <h3 className="text-xs sm:text-base font-bold text-center bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">{feature.title}</h3>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="py-8 sm:py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center mb-8 text-cyan-400">
            User Reviews
          </h2>

          <div className="relative">
            <div className="overflow-hidden">
              <div
                className="flex transition-transform duration-500 ease-in-out"
                style={{ transform: `translateX(-${activeReview * 100}%)` }}
              >
                {REVIEWS.map((review, index) => (
                  <div
                    key={index}
                    className="w-full flex-shrink-0 px-2"
                  >
                    <div className="bg-slate-800/50 backdrop-blur-sm border-2 rounded-xl p-6 max-w-2xl mx-auto"
                      style={{
                        borderImage: 'linear-gradient(135deg, rgba(34, 176, 255, 0.5), rgba(111, 212, 255, 0.2)) 1'
                      }}
                    >
                      <div className="flex items-start gap-4 mb-4">
                        <div className="w-14 h-14 rounded-full flex items-center justify-center flex-shrink-0 border-2"
                          style={{
                            background: 'linear-gradient(135deg, rgba(34, 176, 255, 0.2), rgba(111, 212, 255, 0.1))',
                            borderImage: 'linear-gradient(135deg, #22B0FF, #6FD4FF) 1'
                          }}
                        >
                          <User className="w-7 h-7 text-cyan-400" />
                        </div>
                        <div className="flex-1">
                          <p className="font-bold text-white text-lg">{review.author}</p>
                          <p className="text-sm text-cyan-400">{review.title}</p>
                          <p className="text-xs text-slate-400">{review.location}</p>
                        </div>
                      </div>
                      <div className="bg-slate-900/30 rounded-lg p-4 border-l-4 border-cyan-500/50">
                        <p className="text-slate-200 leading-relaxed">
                          "{review.text}"
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-center gap-2 mt-6">
              {REVIEWS.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setActiveReview(index)}
                  className={`h-2 rounded-full transition-all ${
                    index === activeReview ? 'bg-cyan-500 w-8' : 'bg-slate-600 w-2'
                  }`}
                  aria-label={`Go to review ${index + 1}`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      <div className="bg-black py-3 overflow-hidden border-t border-b border-slate-800">
        <div className="flex animate-marquee whitespace-nowrap">
          {[...TICKER_ITEMS, ...TICKER_ITEMS].map((item, index) => (
            <div key={index} className="inline-flex items-center mx-6 text-sm">
              <span className="font-bold text-white mr-2">{item.ticker}</span>
              <span className="text-slate-400 mr-2">{item.name}</span>
              <span className={`font-medium ${item.isUp ? 'text-emerald-400' : 'text-red-400'}`}>
                {item.change}
              </span>
            </div>
          ))}
        </div>
      </div>

      <footer className="bg-slate-900 py-6 sm:py-8 px-6">
        <div className="max-w-6xl mx-auto">
          <h3 className="text-xl sm:text-2xl font-bold text-blue-400 mb-4 text-center">
            Educational Disclosure
          </h3>

          <div className="space-y-3">
            {DISCLOSURE_SECTIONS.map((section, index) => (
              <div key={index} className="bg-slate-800/30 rounded-lg p-3 sm:p-4">
                <h4 className="text-sm sm:text-base font-semibold text-blue-400 mb-1">
                  {section.title}:
                </h4>
                <p className="text-slate-400 text-xs sm:text-sm leading-relaxed">
                  {section.content}
                </p>
              </div>
            ))}
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800 text-center">
            <p className="text-slate-400 text-xs sm:text-sm mb-2">
              © 2025 AI Data Education System. AI Stock Analyzer.
            </p>
            <p className="text-slate-500 text-xs">
              The content on this site is provided as part of an educational program for AI and data learning.
            </p>
          </div>
        </div>
      </footer>

      {showModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6"
          style={{
            background: 'rgba(15, 23, 42, 0.85)',
            backdropFilter: 'blur(8px)'
          }}
          onClick={(e) => e.target === e.currentTarget && closeModal()}
        >
          <div
            className="border border-cyan-500/30 rounded-2xl max-w-2xl w-full p-6 sm:p-8 relative shadow-2xl"
            style={{
              background: 'rgba(30, 41, 59, 0.95)',
              backdropFilter: 'blur(20px)',
              animation: 'modalSlideIn 0.3s ease-out'
            }}
          >
            <button
              onClick={closeModal}
              className="absolute top-4 right-4 text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-6 h-6" />
            </button>

            <h3 className="text-2xl font-bold text-white mb-6">
              Analyzing: <span className="text-cyan-400">{analyzedSymbol}</span>
            </h3>

            {isAnalyzing ? (
              <div>
                <div className="text-center mb-8">
                  <div className="inline-block w-16 h-16 border-4 border-slate-700 border-t-cyan-500 rounded-full animate-spin mb-4"></div>
                  <p className="text-slate-300">
                    Processing market data for <span className="font-semibold text-cyan-400">{analyzedSymbol}</span>…
                  </p>
                </div>

                <div className="mb-8">
                  <div className="h-3 bg-slate-700 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-cyan-500 to-blue-500 transition-all duration-300 ease-linear"
                      style={{ width: `${analysisProgress}%` }}
                    ></div>
                  </div>
                </div>

                <div className="space-y-3">
                  {ANALYSIS_STEPS.map((step, index) => {
                    const isActive = currentStep === index + 1;
                    const isCompleted = completedSteps.includes(index);
                    return (
                      <div
                        key={index}
                        className={`text-sm transition-all duration-300 flex items-start gap-2 ${
                          isCompleted
                            ? 'text-slate-400'
                            : isActive
                            ? 'text-white font-semibold'
                            : 'text-slate-600'
                        }`}
                      >
                        {isCompleted && <CheckCircle className="w-4 h-4 text-cyan-500 mt-0.5 flex-shrink-0" />}
                        {!isCompleted && <span className="w-4 flex-shrink-0"></span>}
                        <span>{step}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            ) : (
              <div style={{ animation: 'fadeIn 0.3s ease-out' }}>
                <div className="text-center mb-6">
                  <div className="inline-flex items-center justify-center w-16 h-16 bg-cyan-500/20 rounded-full mb-4">
                    <CheckCircle className="w-10 h-10 text-cyan-500" />
                  </div>
                  <h4 className="text-2xl font-bold text-white mb-2">Analysis Complete!</h4>
                  <p className="text-slate-300">
                    Your AI-generated analysis for <span className="font-semibold text-cyan-400">{analyzedSymbol}</span> is ready
                  </p>
                </div>

                <div className="bg-slate-900/50 rounded-lg p-4 mb-6">
                  <p className="text-slate-300 text-sm leading-relaxed">
                    {trafficLink?.url
                      ? 'Click below to access your complete analysis report with detailed insights, metrics, and AI-powered recommendations.'
                      : 'Click below to receive your comprehensive analysis via WhatsApp with key metrics, trend analysis and risk assessments.'
                    }
                  </p>
                </div>

                <button
                  onClick={handleConversionClick}
                  className="w-full bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600 text-white py-4 px-6 rounded-lg font-semibold text-lg transition-all shadow-lg hover:shadow-cyan-500/50 active:scale-[0.98] flex items-center justify-center gap-3"
                >
                  {trafficLink?.url ? (
                    <>
                      <TrendingUp className="w-6 h-6" />
                      Get Full Analysis Report
                    </>
                  ) : (
                    <>
                      <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>
                      </svg>
                      Get Analysis via WhatsApp
                    </>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      <style>{`
        @keyframes marquee {
          0% {
            transform: translateX(0);
          }
          100% {
            transform: translateX(-50%);
          }
        }
        @keyframes marquee-reverse {
          0% {
            transform: translateX(-50%);
          }
          100% {
            transform: translateX(0);
          }
        }
        .animate-marquee {
          animation: marquee 30s linear infinite;
        }
        .animate-marquee-reverse {
          animation: marquee-reverse 20s linear infinite;
        }
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        @keyframes modalSlideIn {
          from {
            opacity: 0;
            transform: scale(0.95) translateY(-20px);
          }
          to {
            opacity: 1;
            transform: scale(1) translateY(0);
          }
        }
      `}</style>
    </div>
  );
}
