// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-template-registry.js
// Generated at: 2026-02-08T08:21:31.608Z
// Templates found: ai-stock-analyzer, ai-stock-edu-learn, ai-stock-insights, ai-stock-intelligence, ai-stock-oracle, ai-stock-pro-enterprise, ai-stock-tech-analysis, ai-stock-usa, ai-stock-usa2, ai-stock-usa3, jp-stock-ai, signm-stock-analysis, smart-money-flow-universal, smartmoney-rank-default

import { ComponentType } from 'react';
import { TemplateProps } from '../../templates/types';

export const templateRegistry: Record<string, () => Promise<{ default: ComponentType<TemplateProps> }>> = {
  'ai-stock-analyzer': () => import('../../templates/ai-stock-analyzer/index'),
  'ai-stock-edu-learn': () => import('../../templates/ai-stock-edu-learn/index'),
  'ai-stock-insights': () => import('../../templates/ai-stock-insights/index'),
  'ai-stock-intelligence': () => import('../../templates/ai-stock-intelligence/index'),
  'ai-stock-oracle': () => import('../../templates/ai-stock-oracle/index'),
  'ai-stock-pro-enterprise': () => import('../../templates/ai-stock-pro-enterprise/index'),
  'ai-stock-tech-analysis': () => import('../../templates/ai-stock-tech-analysis/index'),
  'ai-stock-usa': () => import('../../templates/ai-stock-usa/index'),
  'ai-stock-usa2': () => import('../../templates/ai-stock-usa2/index'),
  'ai-stock-usa3': () => import('../../templates/ai-stock-usa3/index'),
  'jp-stock-ai': () => import('../../templates/jp-stock-ai/index'),
  'signm-stock-analysis': () => import('../../templates/signm-stock-analysis/index'),
  'smart-money-flow-universal': () => import('../../templates/smart-money-flow-universal/index'),
  'smartmoney-rank-default': () => import('../../templates/smartmoney-rank-default/index'),
};

export const availableTemplates = [
  'ai-stock-analyzer',
  'ai-stock-edu-learn',
  'ai-stock-insights',
  'ai-stock-intelligence',
  'ai-stock-oracle',
  'ai-stock-pro-enterprise',
  'ai-stock-tech-analysis',
  'ai-stock-usa',
  'ai-stock-usa2',
  'ai-stock-usa3',
  'jp-stock-ai',
  'signm-stock-analysis',
  'smart-money-flow-universal',
  'smartmoney-rank-default',
] as const;
